### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Zumbalamambo** [Oscheibe/ARIndoorNav#1]
Thanks for the great repo. Please share the details about how to get it working with other environments?

**Comment by Oscheibe** [comment]
Thanks for the wait. You can check out my updated [README ](https://github.com/Oscheibe/ARIndoorNav/blob/master/README.md) or the [documentation ](https://github.com/Oscheibe/ARIndoorNav/blob/master/Documentation/ARCampus%20Navigation%20-%20Documentation.pdf)that goes into more detail.
