### ISSUE TITLE
Hi Oscheibe how can i contact you 

### ISSUE THREAD

**Issue by johnZone99** [Oscheibe/ARIndoorNav#2]

**Comment by Oscheibe** [comment]
Greeting!
Just send me a mail over contact.oliver.scheibert@gmail.com. 
I'm almost finished with this project and will be updating the READ.ME file within the next month to actually explain what this project does and how it works. If you have any specific questions you can open up a new issue or for more private questions, send an email.

**Comment by dineshkick** [comment]
How to create map in unity or we can use drawing file and please send me
the steps to create map and others
